from . import res_company
from . import gst_details
from . import security_policy
from . import change_password_user
from . import res_users
from . import res_partner
from . import gst_integration
from . import contrainer_type_edi
from . import shipping_line_transporters
from . import container_facilities
from . import master_port_data
from . import cms_parties_type
from . import res_groups
from . import container_type_data
from . import container_master
from . import product_template
from . import master_hsn_code
from . import gst_credentials
from . import help_document
from . import res_company_locations
from . import movement_setting
from . import location_shipping_line_mapping
from . import location_invoice_setting
from . import seal_management
from . import lolo_charge
from . import lolo_charge_lines
from . import many2many_options
