{
    'name' : 'Empezar Inventory',
    'summary': 'Empezar Inventory',
    'category' : 'Empezar/Inventory',
    'version': '17.0.1.0.0',
    'depends' : ['base','empezar_base'],
    'author': 'Codetrade.io',
    'website': 'https://www.codetrade.io/',
    'license': 'LGPL-3',
    'description': """Empezar Inventory""",
    "data": [
        "data/ir_cron_data.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/upload_inventory_views.xml",
        "views/damage_condition_views.xml",
        "wizard/upload_inventory_wizard_views.xml",
        "views/update_container_status_views.xml",
        "wizard/upload_container_status_views.xml",
        "views/container_inventory_view.xml",
        "views/hold_release_containers_views.xml",
        "views/hold_reason.xml",
        "wizard/hold_release_wizard.xml",
        "wizard/release_container.xml",
        "data/hold_reason.xml",
    ],
    'installable': True,
    'application': True,
    "assets": {
        "web.assets_backend": [
            "empezar_inventory/static/src/xml/**/*",
            "empezar_inventory/static/src/js/**/*",
            "empezar_inventory/static/src/css/**/*",
            "empezar_inventory/static/src/images/**/*",
        ],
    },
}
