{
    'name': 'Empezar Move Out',
    'summary': 'Module for managing container move-out operations.',
    'category': 'Empezar/Move Out',
    'version': '17.0.1.0.0',
    'depends': ['empezar_base', 'empezar_inventory', 'empezar_delivery_order', 'empezar_vessel_booking', 'empezar_move_in'],
    'author': 'Codetrade.io',
    'website': 'https://www.codetrade.io/',
    'license': 'LGPL-3',
    "data": [
        "data/seal_threshold_mail_template_data.xml",
        "data/gate_pass_mo_data.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/move_out_view.xml",
        "views/vessel_booking.xml",
        "views/move_in_views.xml",
        "views/container_detail_delivery.xml",
        "views/container_inventory.xml",
        "views/seal_view_history.xml",
        "views/seal_history.xml",
        "views/view_allocation_details.xml",
        "reports/move_out_report_action.xml",
        "reports/move_out_report.xml",
    ],
    'installable': True,
    'application': True,
    "assets": {
        "web.assets_backend": [
            "empezar_move_out/static/src/css/**/*",
            "empezar_move_out/static/src/xml/**/*",
            "empezar_move_out/static/src/js/**/*",
        ],
    },
}
