{
    "name": "Empezar Base",
    "summary": "Empezar Base",
    "category": "Empezar/base",
    "version": "17.0.1.0.0",
    "depends": [
        "base",
        "mail",
        "contacts",
        "sale_management",
        "stock",
        "web",
        "l10n_in"
    ],
    "author": "Codetrade.io",
    "website": "https://www.codetrade.io/",
    "license": "LGPL-3",
    "description": """Empezar Base""",
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/res_partner_data.xml",
        "data/gst_credentials_data.xml",
        "data/product_tag_data.xml",
        "data/cms_parties_type_data.xml",
        "data/seal_mail_template_data.xml",
        "data/many2many_options_data.xml",
        "views/res_company_views.xml",
        "views/security_policy_views.xml",
        "views/menu_change_views.xml",
        "views/change_password_wizard_views.xml",
        "views/res_users_views.xml",
        "views/res_partner_views.xml",
        "views/gst_integration_views.xml",
        "views/container_type_edi_views.xml",
        "views/shipping_line_transporters_views.xml",
        "views/container_facilities.xml",
        "views/master_port_data.xml",
        "views/res_partner_parties_views.xml",
        "views/res_groups_views.xml",
        "views/container_type_data_views.xml",
        "views/container_masters_views.xml",
        "views/product_template_views.xml",
        "views/master_hsn_code_views.xml",
        "views/gst_details_views.xml",
        "views/gst_credentials_views.xml",
        "views/res_company_location_views.xml",
        "views/help_document_views.xml",
        "views/location_shippine_line_mapping_views.xml",
        "views/location_invoice_setting_views.xml",
        "views/seal_management_views.xml",
        'views/lolo_charge.xml',
        'views/lolo_charge_lines.xml',
        "views/help_button_tree.xml",
        'wizard/lolo_charges_import_wizard.xml',
        'wizard/seal_management_wizard.xml',
    ],
    "installable": True,
    'application': True,
    "assets": {
        "web.assets_backend": [
            "empezar_base/static/src/css/company_form_view.scss",
            "empezar_base/static/src/css/style.css",
            "empezar_base/static/src/js/company_form_view_display_notification.js",
            "empezar_base/static/src/js/list_view_display_notification.js",
            "empezar_base/static/src/js/password_validation.js",
            "empezar_base/static/src/js/restrict_gst_details_auto_save.js",
            "empezar_base/static/src/boolean_eye/**/*",
            "empezar_base/static/src/js/help_button.js",
            "empezar_base/static/src/xml/**/*",
            "empezar_base/static/src/js/lolo_charges_button.js",
            "empezar_base/static/src/js/seal_button.js",
            "empezar_base/static/src/js/users_button.js",
            "empezar_base/static/src/js/groups_button.js",
            "empezar_base/static/src/js/company_button.js",
            "empezar_base/static/src/js/disable_records.js",
        ],
    },
}
