from . import test_company_profile
from . import test_security_policy
from . import test_user_profile
from . import test_partner_profile
from . import test_product_template
from . import test_shipping_line_transporters
from . import test_container_master
from . import test_container_type_data
from . import test_contrainer_type_edi
from . import test_master_hsn_code
from . import test_master_port_data
from . import test_container_facilities
from . import test_res_groups
from . import test_gst_details
from . import test_help_document
from . import test_company_locations
from . import test_movement_setting
from . import test_location_invoice_setting
from . import test_location_shipping_line_mapping
from . import test_lolo_charge
from . import test_lolo_charges_import_wizard
from . import test_seal_management_wizard
