{
    'name': 'Empezar Account Invoices',
    'summary': 'Module for managing account invoice operations.',
    'category': 'Empezar/Account Invoices',
    'version': '17.0.1.0.0',
    'depends': ['empezar_base', 'empezar_move_in', 'empezar_move_out','fiscal_year'],
    'author': 'Codetrade.io',
    'website': 'https://www.codetrade.io/',
    'license': 'LGPL-3',
    "data": [
        "data/invoice_number_generate.xml",
        "data/credit_note_sequence.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/container_master_views.xml",
        "views/pending_invoices.xml",
        "views/move_in_invoice_view.xml",
        "views/move_out_invoice_view.xml",
        "views/e_invoice_credentials.xml",
        "views/invoice.xml",
        "views/credit_note_invoice.xml",
        "views/monthly_lock.xml",
        "views/cancellation_reason.xml",
        "wizard/container_history.xml",
        "wizard/e_invoice_wizard.xml",
        "wizard/monthly_lock.xml",
        "wizard/invoice_cancellation_wizard.xml",
        "wizard/credit_note_cancellation_wizard.xml",
        "wizard/e_credit_note_wizard.xml",
        'reports/move_in_out_invoice_report.xml',
        'reports/move_in_out_invoice_report_action.xml',
        'reports/credit_note_invoice_report.xml'
    ],
    'installable': True,
    'application': True,
    "assets": {
        "web.assets_backend": [
            "empezar_account_invoices/static/src/css/**/*",
            "empezar_account_invoices/static/src/xml/**/*",
            "empezar_account_invoices/static/src/js/**/*",
        ],
    },
}
