# -*- coding: utf-8 -*-

from odoo import fields, models, _, api


class EDILogs(models.Model):
    _name = "edi.logs"
    _rec_name = "location_id"
    _description = "Edi Logs"
    _order = "create_date desc"

    location_id = fields.Many2one('res.company', string="Location")
    shipping_line_id = fields.Many2one('res.partner', string="Shipping Line",
                                       domain="[('is_shipping_line', '=', True)]")
    type = fields.Selection([
        ('move_in', 'Move In'),
        ('move_out', 'Move Out')
    ], string="Type")
    file = fields.Many2one("ir.attachment", string="File Details")
    container_count = fields.Integer(string="Container Count")
    email_sent = fields.Selection([
        ('yes', 'Yes'),
        ('no', 'No'),
    ])
    edi_sent_on = fields.Datetime(string="Edi Sent On")
    status = fields.Selection([
        ('success', 'Success'),
        ('error', 'Error')
    ])
    generated_by = fields.Char(string="Generated By", default="System")
    move_in_ids = fields.Many2many("move.in", string="Move IN")
    move_out_ids = fields.Many2many("move.out", string="Move Out")
    ftp_upload = fields.Selection([
        ('yes','Yes'),
        ('no','No'),
    ])

    def action_download_file(self):
        """ Trigger file download """
        for record in self:
            if record.file:
                # Return file as a response for download
                return {
                    'type': 'ir.actions.act_url',
                    'url': f'/web/content/{record.file.id}?download=true',
                    'target': 'self',
                }
